### PR TITLE
Improve SCSS

### PR DESCRIPTION
**Pull request by moeenio**
- Split SCSS over multiple files (base, variables, components)
- Use more SCSS variables

I'm new to SASS tho, not sure if I'm using best practices.
Also, SASS recommends [not to use @import anymore](https://sass-lang.com/documentation/at-rules/import).

Thoughts?
cc @micahlt @Hexsphere

### CODE REVIEW

**Comment by moeenio** [comment]
cc @Scratch-Client-4/frontend

**Comment by VFDan** [comment]
Personally, I prefer Less, but I could help you a bit with SCSS

**Comment by moeenio** [comment]
> Personally, I prefer Less, but I could help you a bit with SCSS

I too prefer LESS, but the project's already in SCSS. I didn't want to change. I'd love using LESS, but I guess we need an approval from others at @Scratch-Client-4/frontend

**Comment by VFDan** [comment]
Why are you using CSS vars along with SCSS?

**Comment by retronbv** [comment]
I’m confused what is scss is it the same as css bc it looks the same

**Comment by moeenio** [comment]
> Why are you using CSS vars along with SCSS?

CSS vars are mofified by JS to switch between light/dark mode. I didn't make this tho, it's @micahlt.

**Comment by micahlt** [comment]
@locness3 @VFDan To be honest, this is my first time using Sass, and I'm just using it because @Hexsphere recommended it.  I'll talk to him about possibly switching to Less.  The CSS vars are there to allow easy switching between light and dark theme without page reloads.  I wasn't aware `@import` was depreciated- I tend to prefer it.  And great job splitting the code up- I wasn't sure how much fragmentation was best.  And finally, don't get too invested in styling- if anything work on the Javascript end of things because the design team (me, @Hexsphere, and @Ekmand) is still working on design consistency on Figma.  I won't merge this PR until @Hexsphere checks it over.

**Comment by moeenio** [comment]
> I’m confused what is scss is it the same as css bc it looks the same

[SASS](https://sass-lang.org) is a CSS preprocessor, a program that takes a custom syntax, with additional features than plain CSS like variables or nesting and converts it to plain CSS. SCSS is a syntax for SASS.

**Comment by moeenio** [comment]
> I wasn't aware `@import` was depreciated- I tend to prefer it.

CSS @import isn't tho, just SASS's.

**Review by micahlt — APPROVED** [review]
Everything looks good to me!  Waiting on @Hexsphere 's thoughts.

**Comment by moeenio** [comment]
> CSS `@import` isn't tho, just SASS's.
By that I mean the one you use to import webfonts and such.

**Comment by VFDan** [comment]
Should I change the `@import`s? (@locness3)

**Comment by micahlt** [comment]
@VFDan feel free to do so, but in a different PR as this has been merged.

**Comment by VFDan** [comment]
👍

**Comment by moeenio** [comment]
Well, thanks for merging!

**Pull request merged**
