### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by micahlt**
The GNU GPLv3 looks good for our project.  Got questions?  Check out https://choosealicense.com/

### CODE REVIEW

**Comment by moeenio** [comment]
Why not MIT ?

**Comment by micahlt** [comment]
We don't want people distributing paid versions of SC4. It should be free, right?

**Comment by moeenio** [comment]
yeah

**Review by moeenio — APPROVED** [review]

**Comment by Semisol** [comment]
Yes, this project is free.

**Pull request merged**
